---
services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=thepass
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
